#pragma once

//Important variables

enum Vars {
    eVarMenuSelect1 = 1001,
    eVarMenuSelect2 = 1002,
    eVarMenuSelect3 = 1003,
    eVarMenuSelect4 = 1004,
    eVarMenuCount1 = 1005,
    eVarMenuCount2 = 1006,
    eVarMenuPage1 = 1007,
    eVarMenuPage2 = 1008,
    eVarMenuPage3 = 1009,
    eVarMenuKEY = 1010,
    eVarMenuLocal1 = 1011,
    eVarMenuLocal2 = 1012,
    eVarMenuLocal3 = 1013,
    eVarMenuLocal4 = 1014,
    eVarMenuLocal5 = 1015,
    eVarMenuLocal6 = 1016,
    eVarMenuLocal7 = 1017,
    eVarMenuLocal8 = 1018,
    eVarMenuChar1 = 1019,
    eVarMenuChar2 = 1020
};
